# List of options is available from `man 5 alacritty`. Both the man page and this file
# are easy enough to read and understand, so you won't see many comments.

# ==================================================================================================

[general]

# Load Nord theme.
import = [
  "~/.config/alacritty/nord.toml",
]

[window]
startup_mode = "Fullscreen"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12

[mouse]
hide_when_typing = true
