[general]

import = [
  "~/.config/alacritty/nord.toml",
]

[window]
startup_mode = "Fullscreen"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "V", mods = "Control", action = "ToggleViMode" },
]
